version: '3.8'

services:
  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: wisepen-chat-service
        SERVICE_PKG: chat
        SERVICE_PORT: "9200"
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME:-wisepencloud}-chat:${APP_VERSION}
    container_name: ${CHAT_CONTAINER_NAME:-wisepen-chat-service}
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - PROFILE=${PROFILE:-prod}
      - NACOS_SERVER_ADDR=nacos:8848
      - NACOS_NAMESPACE_ID=
      - NACOS_GROUP=DEFAULT_GROUP
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=9200
      - LOG_LEVEL=INFO
    volumes:
      - ../logs/${CHAT_CONTAINER_NAME:-wisepen-chat-service}:/logs
    networks:
      - cloud-infra_cloud-net

networks:
  cloud-infra_cloud-net:
    external: true
    name: cloud-infra_cloud-net