from __future__ import annotations

from datetime import datetime
from typing import Iterable, Protocol

from sandbox.domain.entities import (
    LeaseRecord,
    PoolSnapshot,
    SandboxRecord,
    SandboxState,
    SessionWorkspaceRecord,
    TurnLeaseRecord,
    UserSandboxBindingRecord,
)
from sandbox.domain.interfaces.metrics import MetricsPort


class SandboxRepository(Protocol):
    @property
    def metrics(self) -> MetricsPort: ...

    async def save(self, record: SandboxRecord) -> None: ...
    async def get(self, sandbox_id: str) -> SandboxRecord | None: ...
    async def records_in(self, states: Iterable[SandboxState]) -> list[SandboxRecord]: ...
    async def snapshot(self, *, min_ready: int = 0, target_ready: int = 0) -> PoolSnapshot: ...
    async def transition(
        self, sandbox_id: str, expected: SandboxState, state: SandboxState, *, error: str | None = None
    ) -> SandboxRecord: ...

    async def checkout_ready(
        self,
        request_id: str,
        user_id: str,
        session_id: str,
        lease_ttl_seconds: int,
        user_idle_ttl_seconds: int = 600,
        max_user_bindings: int = 20,
    ) -> tuple[SandboxRecord, LeaseRecord]: ...

    async def activate_user_binding(self, sandbox_id: str) -> SandboxRecord: ...
    async def find_lease(self, lease_id: str) -> SandboxRecord: ...
    async def get_turn_lease(self, lease_id: str) -> TurnLeaseRecord: ...
    async def find_turn_request(self, request_id: str) -> TurnLeaseRecord | None: ...
    async def active_turn_for_session(self, user_id: str, session_id: str) -> TurnLeaseRecord | None: ...
    async def active_turns_for_sandbox(self, sandbox_id: str) -> list[TurnLeaseRecord]: ...

    async def find_user_binding(self, user_id: str) -> UserSandboxBindingRecord | None: ...
    async def binding_for_sandbox(self, sandbox_id: str) -> UserSandboxBindingRecord | None: ...
    async def user_bindings(self) -> list[UserSandboxBindingRecord]: ...
    async def idle_user_bindings(self, now: datetime | None = None) -> list[UserSandboxBindingRecord]: ...
    async def expired_idle_user_bindings(self, now: datetime | None = None) -> list[UserSandboxBindingRecord]: ...

    async def find_workspace(self, user_id: str, session_id: str) -> SessionWorkspaceRecord | None: ...
    async def workspaces_for_user(self, user_id: str) -> list[SessionWorkspaceRecord]: ...
    async def mark_workspace_prepared(self, user_id: str, session_id: str) -> SessionWorkspaceRecord: ...
    async def mark_workspace_dirty(self, user_id: str, session_id: str) -> None: ...
    async def remove_workspace(self, user_id: str, session_id: str) -> bool: ...

    async def close_lease(self, lease_id: str, fencing_token: int) -> SandboxRecord: ...
    async def validate_lease(
        self,
        lease_id: str,
        user_id: str,
        session_id: str,
        fencing_token: int,
        *,
        now: datetime | None = None,
    ) -> SandboxRecord: ...
    async def finish_release(
        self, lease_id: str, idle_ttl_seconds: int, *, error: str | None = None
    ) -> SandboxRecord: ...
    async def clear_binding(self, record: SandboxRecord) -> None: ...

    async def prepare_ready(self, record: SandboxRecord, readiness_token: str) -> int: ...
    async def return_ready(
        self, sandbox_id: str, health_token: str, expected_generation: int
    ) -> SandboxRecord: ...
    async def expired_turn_leases(self, now: datetime | None = None) -> list[TurnLeaseRecord]: ...
    async def records_older_than(self, state: SandboxState, cutoff: datetime) -> list[SandboxRecord]: ...
