[project]
name = "wisepen-chat-service"
version = "0.1.0"
description = "WisePen Chat Microservice: RAG & LLM Orchestration"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Jiazheng Sun", email = "jzsun24@m.fudan.edu.cn" }
]
dependencies = [
    "fastapi",
    "pydantic",
    "pydantic-settings",
    "uvicorn[standard]",
    "dependency_injector",
    "litellm",
    "mem0ai",
    "openai",
    "anthropic",
    "google-genai",
    "dashscope",
    "jsonschema",
    "dicttoxml",
    "lxml",
    "markdown-it-py",
    "mdit-py-plugins",
    "msgspec>=0.21.1",
    "beanie",
    "redis",
    "nacos-sdk-python",
    "pyyaml",
    "langchain_text_splitters",
    "bm25s>=0.3.9",
    "jieba",
    "thulac",
    "numpy>=2.4.6",
    "zeroentropy",
    "wisepen-common",
]
